server:
  port: 9090


spring:
  mvc:
    throw-exception-if-no-handler-found: true
    favicon:
      enabled: false
  resources:
    add-mappings: false



log:
  level:
    runtime: DEBUG
  runtime:
    path: ./loggs