server:
  port: 8989
spring:
  application:
    name: FFAnalisys
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ffy
    username: root
    password: admin
  thymeleaf:
    cache: false

mybatis:
  mapper-locations: classpath:/mapper/*.xml

log:
  runtime:
    level: DEBUG

logpath:
  runtime:
    path: ./log

