server:
  port: 9999
  ssl:
    key-alias: sslserver
    key-store: D:\certificate\server\server.keystore
    key-password: 123456
    key-store-password: 123456
    key-store-provider: SUN
    key-store-type: jks
    enabled: true
    client-auth: want     # 控制是否是双向认证
    trust-store: D:\certificate\server\serverTrust
    trust-store-password: 123456