server:
  port: 8090
  servlet:
    context-path: /api/v1
spring:
  application:
    name: studentManage
  datasource:
    url: jdbc:h2:mem:student
    username: root
    password: root
    driver-class-name: org.h2.Driver
    schema: classpath:db/schema.sql
    data: classpath:db/data.sql
  h2:
    console:
      enabled: true
      path: /h2
      settings:
        web-allow-others: false
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
