server:
  port: 8081

spring:
  application:
    name: multi-datasource-service
  datasource:
    # dynamic-datasource-spring-boot-starter 动态数据源的配置项
    dynamic:
      primary: order-ds
      datasource:
        # 订单order的数据源配置
        order-ds:
          url: jdbc:mysql://127.0.0.1:3306/seata_order?useSSL=false&useUnicode=true&characterEncoding=UTF-8
          driver-class-name: com.mysql.jdbc.Driver
          username: root
          password: admin
        amount-ds:
          url: jdbc:mysql://127.0.0.1:3306/seata_amount?useSSL=false&useUnicode=true&characterEncoding=UTF-8
          driver-class-name: com.mysql.jdbc.Driver
          username: root
          password: admin
        storage-ds:
          url: jdbc:mysql://127.0.0.1:3306/seata_storage?useSSL=false&useUnicode=true&characterEncoding=UTF-8
          driver-class-name: com.mysql.jdbc.Driver
          username: root
          password: admin
      seata: true  # 是否启动对seata的集成
# seata 配置项
seata:
  application-id: ${spring.application.name}  # 应用编号,默认为${spring.application.name}
  tx-service-group: ${spring.application.name}-group  # seata事务组编号, 用于TC 集群名
  # 服务配置项,对应serviceProperties 类
  service:
    # 虚拟组和分组的映射
    vgroup-mapping:
      multi-datasource-service-group: default
    # 分组和 seata 服务的映射
    grouplist:
      default: 127.0.0.1:8091
logging:
  level:
    com.wk.Mapper: debug
    com.wk.service: debug
